### ISSUE TITLE
Getting error in loading the engine 

### ISSUE THREAD

**Issue by Harsh-Vavaiya** [StefanoBerti/ISBFSAR#5]
@StefanoBerti @andrearosasco I've used this command "docker run -it --rm --gpus=all -v "D:/amnt/Quidich_pose_estimation_poc/ISBFSAR":/home/ecub ecub:latest python modules/hpe/hpe.py"

and getting below error. Help me with this.

```
==========
== CUDA ==
==========

CUDA Version 11.3.1

Container image Copyright (c) 2016-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

Ubuntu: True
2023-03-27 07:23:06.763 | INFO     | utils.tensorrt_runner:__init__:22 - Loading yolo engine...
[03/27/2023-07:23:07] [TRT] [E] 1: [stdArchiveReader.cpp::StdArchiveReader::42] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 232, Serialized Engine Version: 213)
[03/27/2023-07:23:07] [TRT] [E] 4: [runtime.cpp::deserializeCudaEngine::66] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "modules/hpe/hpe.py", line 181, in <module>
    h = HumanPoseEstimator(MetrabsTRTConfig(), RealSenseIntrinsics())
  File "modules/hpe/hpe.py", line 42, in __init__
    self.yolo = Runner(model_config.yolo_engine_path)  # model_config.yolo_engine_path
  File "/home/ecub/utils/tensorrt_runner.py", line 36, in __init__
    for binding in engine:
TypeError: 'NoneType' object is not iterable

```

**Comment by andrearosasco** [comment]
Hi @Harsh-Vavaiya, this is probably happening because tensorrt engines are platform dependent.

There should be a `build_engine.py` script that takes the onnx and generate the trt engine on your machine.

@StefanoBerti should know the location of the script

**Comment by steb6** [comment]
Hi @Harsh-Vavaiya , as said by @andrearosasco you need to build the engine on the platform where you want to run the inference.
You can find the scripts needed in [modules/hpe/utils](https://github.com/StefanoBerti/ISBFSAR/tree/main/modules/hpe/setup).
Note that this is a work in progress, so the README is not updated (sorry for that).
The updated work is on [another repository](https://github.com/ergoCub-HSP/Ergocub-Visual-Perception), you may want to take a look there since the code is much more optimized and I plan to release much more.
Do not hesitate to open another issue or write me an e-mail for other problems!

**Comment by Harsh-Vavaiya** [comment]
@StefanoBerti @andrearosasco Thank you, guys !!

**Comment by Harsh-Vavaiya** [comment]
Hi @StefanoBerti, 

I want to use only your hpe extensively into other project. should I use this repo's code or your latest one.? and latest one works with new models (2023's) of metrabs?

**Comment by steb6** [comment]
Hi @Harsh-Vavaiya,
if you want just to use the HPE module, maybe it is bettere if you stick to this code since the other one is more complex.
You have to build the TRT engine starting from the ONNXs.
I uploaded the ONNXs [here](https://drive.google.com/file/d/1BQmdaraDdPc82vw4hp0WrZsX38llwqS7/view?usp=sharing), donwnload them and place them inside `modules/hpe/weights` and run the script `modules/hpe/setup/7_create_engines.py` (you may want to check the path).
After that, you should be able to run the `hpe.py` script.
Note that the creation of the engine requires some time (about 30 minutes).

**Comment by Harsh-Vavaiya** [comment]
@StefanoBerti Thank you for the ONNXs files !!

have you seen the index of metrabs? 
[index](https://omnomnom.vision.rwth-aachen.de/data/metrabs/?C=M&O=D)

see there are new versions of models, I wanna test this one [metrabs_eff2xl_y4_384px_800k_28ds.tar.gz)](https://omnomnom.vision.rwth-aachen.de/data/metrabs/metrabs_eff2xl_y4_384px_800k_28ds.tar.gz)

please, give me your ideas on it. should I only change the input size in your code, or it'll take more efforts?

**Comment by steb6** [comment]
@Harsh-Vavaiya I didn't know that he released new models, thanks for the update!
So it is needed to extract two ONNXs: the one of the backbone and the one of the heads.
It shouldn't be too difficult anyway, you can see how I extracted the ONNXs in the files:
- `modules/hpe/setup/2_extract_bbone_heads.py`
- `modules/hpe/setup/3_extract_bbone_onnx.py`
- `modules/hpe/setup/4_extract_heads_onnx.py`

It should be quite easy to make everything work.
Now I don't have time to do it, but this is a thing that I will try for sure!
